spring:
  application:
    name: to-do-list
    version: 1.0.0
  datasource:
    url: jdbc:postgresql://localhost:5432/to_do_list_db
    username: thallys
    password: thallys
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
